### Post request to create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "John Doe",
    "email": "testemail@gmail.com",
    "address":"123 Main Street",
    "dateOfBirth" : "1995-07-20",
    "registeredDate" : "2024-11-28"
}

###